### ISSUE TITLE
GitHub documentation: Links in wiki pages are broken

### ISSUE THREAD

**Issue by lehnerj** [ganskef/MoCuishle#2]
Most links in [_posts](https://github.com/ganskef/MoCuishle/tree/gh-pages/_posts) that reference a different page in _posts are broken.

How to reproduce:
Go to: https://github.com/ganskef/MoCuishle/blob/gh-pages/_posts/9999-12-31-mocuishle.md
Click on: browse history
You get 404, this URL was requested: https://github.com/ganskef/MoCuishle/blob/gh-pages/_posts/%7B%7B%20site.url%20%7D%7D/browse-history

**Comment by ganskef** [comment]
Hi @lehnerj, thank you for forking the *Mo Cuishle* documentation pages. My English could be ugly sometimes. I'm happy for corrections always.

You've tried to open the links in the *Markdown* sources. Since it's a *GitHub Project Page* instead of an *User Page*, I can't use relative links in `_posts`. The root differs between developement mode and uploaded to *GitHub*. 

If I figure out a way to render the `{{ site.url }}` variable in source presentation, I could fix it.

**Comment by ganskef** [comment]
After migrating to MDwiki links are working at the website and in GitHub sources too, finally.
